apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.app.name }}-service
spec:
    selector:
        app: {{ .Values.app.name }}-pod
    ports:
    - port: {{ .Values.deployment.port }}
      protocol: TCP
      targetPort: {{ .Values.deployment.targetport }}